该页面用于记录服务器管理者们所碰到的一切报错  
并尽可能提供报错的解决步骤.

报错1:
-
```yaml
java.lang.NullPointerException: Cannot invoke  
"io.lumine.xikage.mythicmobs.mobs.MobRegistry.values()" because the return value of  
"io.lumine.xikage.mythicmobs.utils.serialization.wrappedJsonFile.get()" is null
```
-----

* 报错原因: 保存数据出错
* 解决措施: 删除savedata文件夹并检测java版本是否正确

报错2:
-
```yaml
✗ Config Error for Targeter line 'MIR{type=不存在的mm怪}': The 'type' attribute must be a valid MythicMob or MythicEntity type.
```
----

* 报错原因: 所填写的Mythic实体不存在
* 解决措施: 换用有效的Mythic实体

报错3:
---
```yaml
Exception thrown whilst executing task  
  java.lang.NullPointerException  
    at io.lumine.xikage.mythicmobs.players.PlayerManager.lambda$saveAll$116(PlayerManager.java:80)  
    at java.util.concurrent.ConcurrentHashMap.forEach(Unknown Source)  
    at io.lumine.xikage.mythicmobs.players.PlayerManager.saveAll(PlayerManager.java:76)
```
----

* 报错原因: 保存数据出错
* 解决措施: 删除MythicMobs/SavedData文件夹

报错4:
---
```yaml
✗ Config Error for Mechanic line 'varmath{var=变量种类.变量名;e="值"} @self"' in 'Unknown': Variable name must be set
```
----

* 报错原因: 忽略, 提示为变量名未设置